### ISSUE TITLE
There is an error in the test in README（README中test有误）

### ISSUE THREAD

**Issue by FengodChen** [songjiechong/OCTUF#1]
"--sensing-rate" should be used instead of "--sensing_rate" in test, i.e. python test_otuf.py --sensing-rate 0.1/0.25/0.3/0.4/0.5 --test_name Set11/Urban100
（test中应该使用”--sensing-rate“而不是“--sensing_rate”，即python test_octuf.py --sensing-rate 0.1/0.25/0.3/0.4/0.5 --test_name Set11/Urban100）

**Comment by songjiechong** [comment]
Thank you for your comment. Both "--sensing_rate" and "--sensing-rate" are correct. You can try both.

**Comment by FengodChen** [comment]
> Thank you for your comment. Both "--sensing_rate" and "--sensing-rate" are correct. You can try both.

Thank you for your reply. It might be due to compatibility issues, as I encountered errors on my computer. I could only run it normally after I modified it according to the method above.
